notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

presentation:
    resource: "@PresentationBundle/Resources/config/routing.yml"
    prefix:   /

about:
    resource: "@AboutBundle/Resources/config/routing.yml"
    prefix:   /

offer:
    resource: "@OfferBundle/Resources/config/routing.yml"
    prefix:   /

account:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /

flow:
    resource: "@FlowBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    resource: "@HomepageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
