<?php

namespace Personews\FlowBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlowcontentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowcontentRepository extends EntityRepository
{
}
