<?php

namespace Personews\NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DevicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevicesRepository extends EntityRepository
{
}
